/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 22/05/2011, 19:56:50
 */
package com.nubeando.presentacion;

import com.nubeando.modelo.TClase;

/**
 *
 * @author Administrador
 */
public class PanelClase extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public PanelClase() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        scrollUp = new javax.swing.JScrollPane();
        listAtributos = new javax.swing.JList();
        scroolDown = new javax.swing.JScrollPane();
        listMetodos = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        labelNombre.setBackground(new java.awt.Color(153, 153, 255));
        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 0, 0));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("jLabel1");
        labelNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelNombre.setOpaque(true);
        add(labelNombre, java.awt.BorderLayout.NORTH);

        listAtributos.setBackground(new java.awt.Color(204, 204, 204));
        listAtributos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scrollUp.setViewportView(listAtributos);

        add(scrollUp, java.awt.BorderLayout.CENTER);

        listMetodos.setBackground(new java.awt.Color(204, 204, 255));
        listMetodos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scroolDown.setViewportView(listMetodos);

        add(scroolDown, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNombre;
    private javax.swing.JList listAtributos;
    private javax.swing.JList listMetodos;
    private javax.swing.JScrollPane scrollUp;
    private javax.swing.JScrollPane scroolDown;
    // End of variables declaration//GEN-END:variables

    public void setCell(TClase cell) {        
        labelNombre.setText(cell.getNombre());
        if (cell.getAtributos().size() > 0) {
            listAtributos.setListData(cell.getAtributos().toArray());
        }
        if (cell.getMetodos().size() > 0) {
            listMetodos.setListData(cell.getMetodos().toArray());
        }

    }
}
